"""Copy the C files generated by Cython next to their Cython sources.

The ``Cython.Coverage`` plugin of ``coverage.py`` reads the executable lines of
a Cython module from the C file generated from it, which it looks for next to
the source, with the same name. Meson writes that file in the build directory
instead, inside the private directory of the extension module, under the same
relative path as the source, so it is copied to the source tree, where git
ignores it.

Run it from the root of the repository after an editable install, which builds
the package in a subdirectory of ``build``.
"""

import shutil
import sys
from pathlib import Path

PACKAGE = "sklr"
BUILD_DIR = Path("build")

# Meson names the C file of "<name>.pyx" "<name>.pyx.c", and the private
# directory of an extension module "<extension module>.p"
GENERATED_PATTERN = f"*/{PACKAGE}/**/*.p/*.pyx.c"


def main():
    generated = sorted(BUILD_DIR.glob(GENERATED_PATTERN))
    if not generated:
        print(
            f"No C file generated by Cython found in {BUILD_DIR}, matching "
            f"{GENERATED_PATTERN!r}. Install the package in editable mode first",
            file=sys.stderr,
        )
        return 1
    errors = []
    for path in generated:
        build_root = BUILD_DIR / path.relative_to(BUILD_DIR).parts[0]
        source_dir = path.parent.parent.relative_to(build_root)
        name = path.name.removesuffix(".pyx.c")
        if not (source_dir / f"{name}.pyx").exists():
            errors.append(f"{path}: no Cython source {source_dir / name}.pyx")
            continue
        target = source_dir / f"{name}.c"
        shutil.copyfile(path, target)
        print(f"Copied {path} to {target}")
    for error in errors:
        print(error, file=sys.stderr)
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
