#!/usr/bin/Rscript

# Activate the command line arguments
# and get the requirements to install
args <- commandArgs(TRUE)
requirements <- readLines(file(args[1], open="r"))

# Install and activate the devtools package
# to get specific versions of the requirements
install.packages("devtools", dependencies=TRUE)
require(devtools)

for (i in 1:length(requirements))
{
    # Extract the package and the version from the
    # read line according to the separator pattern
    line <- unlist(strsplit(requirements[i], "=="))
    package <- line[1]
    version <- line[2]

    install.packages(package, version=version)
}
